name: Test AWS Runner

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions

jobs:
  test-runner:
    runs-on: self-hosted # This ensures it runs on your AWS self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print system info
        run: |
          echo "Testing the AWS Linux Runner"
          uname -a
          lsb_release -a || cat /etc/os-release
          whoami
          df -h
          free -m

      - name: Test basic commands
        run: |
          echo "Runner is working!"
          pwd
          ls -la
          # cloud-init YAML script for setting up a DevOps environment
